###
### Save new Book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Master and Margarita",
  "author": "Bulgakov",
  "isbn": "00001",
  "price": "100",
  "description": "novel"
}

### Get all Books
GET http://localhost:8080/books

### Get Book by id
GET http://localhost:8080/books/1

