### http://localhost:8080/swagger-ui/index.html
### Save new Book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Poems",
  "author": "Esenin",
  "isbn": "00003",
  "price": "130",
  "description": "Poems"
}

### Get all Books
GET http://localhost:8080/books?page=0&size=3&sort=price,desc&sort=author

### Get Book by id
GET http://localhost:8080/books/1

### Search by params
GET http://localhost:8080/books/search?authorIn=pushkin,esenin,bulgakov&priceMax=150&priceMin=10&titleContains=poems

### Update  Book
PUT http://localhost:8080/books/2
Content-Type: application/json

{
  "title": "Poems",
  "author": "Pushkin",
  "isbn": "00001",
  "price": "150",
  "description": "Poems"
}

### Delete Book by id
DELETE http://localhost:8080/books/1