### http://localhost:8080/swagger-ui/index.html
### Save new Book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Poems",
  "author": "Esenin",
  "isbn": "00003",
  "price": "130",
  "description": "Poems"
}

### Get all Books
GET http://localhost:8080/books?page=0&size=3&sort=price,desc&sort=author

### Get Book by id
GET http://localhost:8080/books/1

### Search by params
GET http://localhost:8080/books/search?authorIn=pushkin,esenin,bulgakov&priceMax=150&priceMin=10&titleContains=poems

### Update  Book
PUT http://localhost:8080/books/2
Content-Type: application/json

{
  "title": "Poems",
  "author": "Pushkin",
  "isbn": "00001",
  "price": "150",
  "description": "Poems"
}

### Delete Book by id
DELETE http://localhost:8080/books/1

#Access key AKIA55N7S4ZILUMUFD45
#Secret access key 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

sudo docker run -p 80:8080 AMAZON_ID.dkr.ecr.eu-central-1.amazonaws.com/online-book-store:latest --spring.datasource.url=jdbc:mysql://online-book-store.cudldxsqywqy.eu-central-1.rds.amazonaws.com:3306/online_book_store --spring.datasource.username=username --spring.datasource.password=password